n1 = int(input('Digite um número: '))
n2 = int(input('Digite um número: '))
n3 = int(input('Digite um número: '))
maior = max(n1, n2, n3)
menor = min(n1, n2, n3)
print('O maior número é o {} \ne o menor número é o {}.' .format(maior, menor))