n = int(input('Digite um número para ver sua tabuada: '))
print('-'*40)
print('A tabuada do',n, 'é:\n{} x {} = {}'. format(n, 1, n*1))
print('{} x {} = {}'. format(n, 1, n*2))
print('{} x {} = {}'. format(n, 1, n*3))
print('{} x {} = {}'. format(n, 1, n*4))
print('{} x {} = {}'. format(n, 1, n*5))
print('{} x {} = {}'. format(n, 1, n*6))
print('{} x {} = {}'. format(n, 1, n*7))
print('{} x {} = {}'. format(n, 1, n*8))
print('{} x {} = {}'. format(n, 1, n*9))
print('{} x {} = {}'. format(n, 1, n*10))
print('-' *40)