brasileirao = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico', 'Atlético-MG', 'Fortaleza', 'São Paulo', 'América-MG', 'Botafogo', 'Santos', 'Goiás', 'Red Bull Bragantino', 'Coritiba', 'Cuiabá', 'Ceará', 'Atlético-GO', 'Avaí', 'Juventude')
print('Classificação final do Brasileirão 2022: Palmeiras, Internacional, Fluminense, Corinthians, Flamengo, Athletico, Atlético-MG, Fortaleza, São Paulo, América-MG, Botafogo, Santos, Goiás, Red Bull Bragantino, Coritiba, Cuiabá, Ceará, Atlético-GO, Avaí, Juventude')
print('-='*50)
print('Os 5 primeiros colocados do último Brasileirão foram: {}.' .format(brasileirao[0:5]))
print('-='*50)
print('Os 4 últimos foram: {}.'.format(brasileirao[16:21]))
print('-='*50)
print(f'Lista dos times do Brasileirão 2022 em ordem alfabética: {sorted(brasileirao)}')
print('-='*50)
print('O SÃO PAULO terminou na {}ª posição do Brasileirão 2022.' .format(brasileirao.index('São Paulo')+1))