import time
print('Vai começar a contagem regressiva!')
time.sleep(3)
for c in range(10, 0, -1):
    time.sleep(1)
    print('10', end= ' ')
    time.sleep(1)
    print('9', end= ' ')
    time.sleep(1)
    print('8', end= ' ')
    time.sleep(1)
    print('7', end= ' ')
    time.sleep(1)
    print('6', end= ' ')
    time.sleep(1)
    print('5', end= ' ')
    time.sleep(1)
    print('4', end= ' ')
    time.sleep(1)
    print('3', end= ' ')
    time.sleep(1)
    print('2', end= ' ')
    time.sleep (1)
    print('1', end= ' ')
    time.sleep(1)
    print('0')
    time.sleep(1)
    print('FELIZ ANO NOVO!!!!!')
    quit()